name: recomm-constraint
channels:
  - defaults
dependencies:
  - python=3.11.10
  - pip
  - matplotlib=3.9.2
  - numpy=1.26.4
  - pandas=2.1.4
  - scipy
  - seaborn
  - tqdm
  - scikit-learn
  - pip:
      - gurobipy==11.0.3
      - implicit==0.7.2
      - ortools==9.11.4210
      - pyyaml==6.0.1
      - annoy==1.17.3
